### ISSUE TITLE
ListInventories - google.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument.

### ISSUE THREAD

**Issue by TomekS98** [googleapis/python-os-config#247]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-os-config/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: win10
  - Python version: Python 3.8.7
  - pip version: pip version 20.3.3
  - `google-cloud-os-config` version:Version: 1.12.4

#### Steps to reproduce

  1. run the code

#### Code example

```python
client2 = osconfig_v1.OsConfigZonalServiceClient() #I do have ['GOOGLE_APPLICATION_CREDENTIALS'] set correctly (other clients work)
parent = f"projects/{project_id}/locations/{instance_location}/instances/"
request = osconfig_v1.ListInventoriesRequest(
                            parent=parent
                        )
page_result = client2.list_inventories(request=request)
```

#### Stack trace
```
Traceback (most recent call last):
  File "PATH\test1\lib\site-packages\google\api_core\grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "PATH\test1\lib\site-packages\grpc\_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "PATH\test1\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Request contains an invalid argument."
	debug_error_string = "UNKNOWN:Error received from peer ipv4: 142.250.203.138:443 {created_time:"2022-10-11T11:10:51.508779112+00:00", grpc_status:3, grpc_message:"Request contains an invalid argument."}"
>



  File "PATH/PycharmProjects/gcp_projects/main.py", line 98, in list_compute_instances_from
    page_result = client2.list_inventories(request=request)
  File "PATH\test1\lib\site-packages\google\cloud\osconfig_v1\services\os_config_zonal_service\client.py", line 1902, in list_inventories
    response = rpc(
  File "PATH\test1\lib\site-packages\google\api_core\gapic_v1\method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "PATH\test1\lib\site-packages\google\api_core\grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument.


```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by parthea** [comment]
Hi @TomekS98,

I was able to reproduce the issue with the code provided. 

https://github.com/googleapis/python-os-config/blob/9c6974e90ac3a366ef052b342e441923f81b898a/google/cloud/osconfig_v1/types/inventory.py#L630-L634

I noticed that the example for `parent` above has an example with `-` as a suffix.

I changed 
`parent = f"projects/{project_id}/locations/{instance_location}/instances/"`
to 
`parent = f"projects/{project_id}/locations/{instance_location}/instances/-"`

in the sample code and the issue appears to be resolved.

Please could you try the following code?
```
client2 = osconfig_v1.OsConfigZonalServiceClient() #I do have ['GOOGLE_APPLICATION_CREDENTIALS'] set correctly (other clients work)
parent = f"projects/{project_id}/locations/{instance_location}/instances/-"
request = osconfig_v1.ListInventoriesRequest(
                            parent=parent
                        )
page_result = client2.list_inventories(request=request)
```

**Comment by TomekS98** [comment]
It's working with the '-', thank you so much!
